version: '2'

services:
  server:
    image: jpetazzo/dockvpn
    container_name: vpn
    privileged: true
    volumes:
      - "./run:/usr/local/sbin/run"
      - "./serveconfig:/usr/local/sbin/serveconfig"
    ports:
      - "8082:1194/tcp"
      - "8083:443/tcp"
    network_mode: "bridge"

  config:
    image: jpetazzo/dockvpn
    container_name: vpn-config
    command: "serveconfig"
    volumes_from:
      - server
    volumes:
      - "./run:/usr/local/sbin/run"
      - "./serveconfig:/usr/local/sbin/serveconfig"
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=vpn.lobr.fr
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=https
      - CERT_NAME=none
    network_mode: "bridge"